name: Remote Server Deploy

on:
  push:
    branches:
      - main       # deploy on push to main branch
  workflow_dispatch: # allow manual "Run workflow"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run SSH commands on server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /home/jisung/work
          git pull origin main
          echo "Deployment completed!"

